# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScrollViewDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ScrollViewDemo
pod 'SwiftVideoGenerator'

  target 'ScrollViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
